# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_online', models.BooleanField(default=0)),
                ('sell_offline', models.BooleanField(default=0)),
                ('trace_stock', models.BooleanField(default=0)),
                ('min_stock', models.IntegerField()),
                ('max_stock', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('reminder_date', models.DateTimeField()),
                ('max_order', models.IntegerField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_unit_stock', models.IntegerField()),
                ('med_unit_stock', models.IntegerField()),
                ('main_unit_price', models.FloatField()),
                ('med_unit_price', models.FloatField()),
                ('expiration', models.DateTimeField()),
                ('purchase_price', models.FloatField()),
                ('purchase_discount', models.IntegerField()),
                ('bounce', models.IntegerField()),
                ('min_amount', models.IntegerField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Pharmacy')),
            ],
        ),
    ]
