# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20170507_2204'),
        ('Stock', '0003_auto_20170508_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinestock',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Branches'),
        ),
    ]
