# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0006_medicinesettings_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinesettings',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='medicinestock',
            name='min_amount',
        ),
        migrations.AlterField(
            model_name='medicinesettings',
            name='reminder_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='expiration',
            field=models.DateField(),
        ),
    ]
