# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sales', '0001_initial'),
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.SalesInvoice'),
        ),
        migrations.AddField(
            model_name='branches',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Pharmacy'),
        ),
    ]
