# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0002_auto_20170427_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512)),
                ('second_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Area')),
            ],
        ),
        migrations.CreateModel(
            name='GenericName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('tax_type', models.SmallIntegerField()),
                ('tax_percent', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='branches',
            old_name='branch_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='discount_perc',
            new_name='discount_percent',
        ),
        migrations.RenameField(
            model_name='coremedicine',
            old_name='comerical_name',
            new_name='commercial_name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='coremedicine',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='branch',
        ),
        migrations.AddField(
            model_name='clients',
            name='allow_negative_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clients',
            name='max_negative_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Branches'),
        ),
        migrations.AddField(
            model_name='employees',
            name='national_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coremedicine',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Brand'),
        ),
        migrations.AlterField(
            model_name='coremedicine',
            name='generic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.GenericName'),
        ),
        migrations.AlterField(
            model_name='coremedicine',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Licence'),
        ),
        migrations.AlterField(
            model_name='coremedicine',
            name='small_unit',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='coremedicine',
            name='small_unit_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='coremedicine',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.MedicineType'),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Clients'),
        ),
        migrations.AddField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Governorate'),
        ),
        migrations.AddField(
            model_name='category',
            name='tax_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.TaxGroup'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.City'),
        ),
        migrations.AddField(
            model_name='coremedicine',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Category'),
        ),
    ]
