# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_branches_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Area'),
        ),
        migrations.AddField(
            model_name='branches',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.City'),
        ),
        migrations.AddField(
            model_name='branches',
            name='governorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Governorate'),
        ),
    ]
