# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20170719_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
