# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0004_branches_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_online', models.BooleanField(default=True)),
                ('sell_offline', models.BooleanField(default=True)),
                ('trace_stock', models.BooleanField(default=False)),
                ('min_stock', models.IntegerField(default=1)),
                ('max_stock', models.IntegerField(default=1000)),
                ('reminder_date', models.IntegerField(default=60)),
                ('show_main_phone', models.BooleanField(default=True)),
                ('show_branch_phone', models.BooleanField(default=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Pharmacy')),
            ],
        ),
    ]
