# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='max_order',
            field=models.IntegerField(default=100),
        ),
    ]
