# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20170719_0502'),
        ('System_Setting', '0002_systemsettings_max_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_online', models.BooleanField(default=True)),
                ('sell_offline', models.BooleanField(default=True)),
                ('trace_stock', models.BooleanField(default=False)),
                ('min_stock', models.IntegerField(default=1)),
                ('max_stock', models.IntegerField(default=1000)),
                ('reminder_date', models.IntegerField(default=60)),
                ('max_order', models.IntegerField(default=100)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.CoreMedicine')),
            ],
        ),
    ]
