# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('sales_price', models.FloatField(default=0.0)),
                ('purchase_price', models.FloatField(default=0.0)),
                ('net_price', models.FloatField(default=0.0)),
                ('bounce', models.FloatField()),
                ('discount', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=200)),
                ('tax', models.FloatField(default=0.0)),
                ('expiration_date', models.DateTimeField()),
                ('supplier', models.CharField(max_length=200)),
                ('process_date', models.DateTimeField(auto_now_add=True)),
                ('branch_name', models.CharField(max_length=200)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseitems',
            name='purchase_invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchases.PurchasesInvoice'),
        ),
    ]
