# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0003_auto_20170507_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.SmallIntegerField(default=1)),
                ('current_balance', models.FloatField(default=0)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Treasury')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('done_by', models.CharField(max_length=128)),
                ('comment', models.CharField(max_length=512)),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Treasury')),
            ],
        ),
    ]
