# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20170507_2204'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField()),
                ('debit', models.FloatField()),
                ('comment', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Clients')),
            ],
        ),
    ]
