# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customeraccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccounts',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customeraccounts',
            name='debit',
            field=models.FloatField(default=0),
        ),
    ]
