# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_employees_salary'),
        ('Accounts', '0003_auto_20170522_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=64)),
                ('account_number', models.IntegerField()),
                ('balance', models.FloatField()),
                ('currency', models.CharField(max_length=64)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Pharmacy')),
            ],
        ),
    ]
