# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_expensecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasury',
            old_name='current_balance',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='treasury',
            name='account_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='treasury',
            name='currency',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='treasuryauth',
            name='deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treasuryauth',
            name='withdraw',
            field=models.BooleanField(default=False),
        ),
    ]
