# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date_added',
            new_name='date',
        ),
    ]
