# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=200)),
                ('sales_price', models.FloatField(default=0.0)),
                ('purchase_price', models.FloatField(default=0.0)),
                ('net_price', models.FloatField(default=0.0)),
                ('discount', models.IntegerField(max_length=3)),
                ('reverse', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('total_price', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=0)),
                ('client_name', models.CharField(max_length=60)),
                ('sold_by', models.CharField(max_length=60)),
                ('branch_name', models.CharField(max_length=200)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Pharmacy')),
            ],
        ),
    ]
