# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitems',
            old_name='medicine',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='date_time',
            new_name='date',
        ),
    ]
