# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20170507_2204'),
        ('Sales', '0002_auto_20170507_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Branches'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.MedicineStock'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Employees'),
        ),
    ]
