# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_auto_20170507_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='pharmacy',
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
