# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_auto_20170507_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Clients'),
        ),
    ]
