# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_auto_20170507_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.SalesInvoice'),
        ),
    ]
