# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_invoiceitems_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.SalesInvoice'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Branches'),
        ),
    ]
