# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_auto_20170508_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitems',
            old_name='sales_price',
            new_name='main_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='reverse',
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='main_unit_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='med_unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='med_unit_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
