# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_auto_20170508_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitems',
            name='net_price',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='purchase_price',
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='main_unit_price',
            field=models.FloatField(default='Stock.MedicineStock.main_unit_price'),
        ),
    ]
