# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0009_auto_20170508_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='client_name',
            new_name='customer',
        ),
    ]
