# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0010_auto_20170522_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='comment',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
